/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : InquiryId,
  'name' : string,
  'email' : string,
  'courseInterest' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export type InquiryId = bigint;
export interface OverallStats {
  'totalPlacements' : bigint,
  'highestPackage' : number,
  'companiesCount' : bigint,
  'avgSalary' : number,
}
export interface PlacementRecord {
  'year' : bigint,
  'placementRate' : bigint,
  'topCompanies' : Array<string>,
  'highestLPA' : number,
  'courseName' : string,
  'courseId' : string,
  'avgLPA' : number,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getOverallStats' : ActorMethod<[], OverallStats>,
  'getPlacementStats' : ActorMethod<[], Array<PlacementRecord>>,
  'submitContactInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitCourseInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];