/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactInquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const OverallStats = IDL.Record({
  'totalPlacements' : IDL.Nat,
  'highestPackage' : IDL.Float64,
  'companiesCount' : IDL.Nat,
  'avgSalary' : IDL.Float64,
});
export const PlacementRecord = IDL.Record({
  'year' : IDL.Nat,
  'placementRate' : IDL.Nat,
  'topCompanies' : IDL.Vec(IDL.Text),
  'highestLPA' : IDL.Float64,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
  'avgLPA' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
  'getPlacementStats' : IDL.Func([], [IDL.Vec(PlacementRecord)], ['query']),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitCourseInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactInquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const OverallStats = IDL.Record({
    'totalPlacements' : IDL.Nat,
    'highestPackage' : IDL.Float64,
    'companiesCount' : IDL.Nat,
    'avgSalary' : IDL.Float64,
  });
  const PlacementRecord = IDL.Record({
    'year' : IDL.Nat,
    'placementRate' : IDL.Nat,
    'topCompanies' : IDL.Vec(IDL.Text),
    'highestLPA' : IDL.Float64,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
    'avgLPA' : IDL.Float64,
  });
  
  return IDL.Service({
    'getContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
    'getPlacementStats' : IDL.Func([], [IDL.Vec(PlacementRecord)], ['query']),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitCourseInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };